name: Run

on:
  push:
    branches:
      - "main"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          bazel run --config=asan :main

